name: Lab 3 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: ทำงานบน GitHub Hosted Runner ---
  ci-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Scan with Sonarqube
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=Gwangyasation_Test-DevSecOps
            -Dsonar.organization=gwangyasation
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # เปลี่ยน 'node-remote-test' เป็นชื่อ image ของคุณ
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-remote-test:latest

  # --- JOB 2: ทำงานบน Self-hosted Runner (เครื่อง VM ของคุณ) ---
  cd-process:
    needs: ci-process # ต้องรอให้ Job 1 เสร็จก่อน
    runs-on: self-hosted # ระบุให้รันบนเครื่อง VM ที่คุณต่อไว้
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-remote-test:latest

      - name: Stop Old Container
        run: |
          docker stop my-app-container || true
          docker rm my-app-container || true

      - name: Start New Container
        run: |
          docker run -d \
            --name my-app-container \
            -p 3000:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/node-remote-test:latest
